apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: DEPLOYMENT_NAME
  name: DEPLOYMENT_NAME
spec:
  selector:
    matchLabels:
      app: DEPLOYMENT_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: DEPLOYMENT_NAME
    spec:
      containers:
      - image: IMAGE_NAME
        name: DEPLOYMENT_NAME
        resources: {}