AIRFLOW = "airflow" # Orchestrator
AWS = "aws" # Key vault / Secrets
AZURE = "azure" # Artifact store, Key vault
AZUREML = "azureml" # Step controller (training)
EVIDENTLY = "evidently" # Profiling
GCP = "gcp" # Artifact store
KUBEFLOW = "kubeflow" # Orchestrator, Metadata store
MLFLOW = "mlflow" # Deployer, logging, context
PYTORCH = "pytorch" # Special producers
PYTORCH_L = "pytorch_lightning" # Special producers
S3 = "s3" # Artifact store
SAGEMAKER = "sagemaker" # Step controller (training / inference)
SELDON = "seldon" # Deployer (with Alibi we can do monitoring too!)
SKLEARN = "sklearn" # Special train, split, eval steps; Producers
TENSORFLOW = "tensorflow" # Special train step; Producers
WHYLOGS = "whylogs" # Data / Model profiling
VERTEX = "vertex" # Orchestrator, Step controller