apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    app: DEPLOYMENT_NAME
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: DEPLOYMENT_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080